---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Install Extra Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: server.packages
  when: server.packages is defined

- name: Configure the timezone
  become: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: yes
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

#- name: Set default system language pack
#  shell: locale-gen {{server.locale}}
#  become: yes

- name: Set default system language pack
  shell: export LANGUAGE=en_US.UTF-8

- name: Set default system language pack
  shell: export LANG=en_US.UTF-8

- name: Set default system language pack
  shell: export LC_ALL=en_US.UTF-8

- name: Set default system language pack
  shell: locale-gen en_US.UTF-8

- name: Set default system language pack
  become: yes
  shell: sudo dpkg-reconfigure locales

